// PDF documents (rental agreement, vehicle statements) built with jsPDF.
// jsPDF is imported lazily so it only loads when a download is clicked.
import { rentalDays, fmtDate } from "./bookingsStore.js";
import { getBusiness } from "./businessStore.js";

const INK = "#0a0d12";
const SOFT = "#545c68";
const MUTE = "#8b929d";
const LINE = "#dde2ea";

const kes = (n) => `KES ${n.toLocaleString("en-KE")}`;

/* Shared page chrome: brand header + footer. Returns the content start Y. */
function header(doc, title, refLine) {
  doc.setFillColor(INK);
  doc.rect(0, 0, 210, 26, "F");
  doc.setTextColor("#ffffff");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.text("Ardena", 16, 12);
  doc.setFontSize(8.5);
  doc.setFont("helvetica", "normal");
  doc.setTextColor("#9aa3af");
  doc.text("for Business · business.ardena.co.ke", 16, 18);

  doc.setTextColor("#ffffff");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.text(title, 194, 12, { align: "right" });
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor("#9aa3af");
  doc.text(refLine, 194, 18, { align: "right" });
  return 38;
}

function footer(doc) {
  const page = doc.internal.pageSize.getHeight();
  doc.setDrawColor(LINE);
  doc.line(16, page - 16, 194, page - 16);
  doc.setFontSize(7.5);
  doc.setTextColor(MUTE);
  doc.text(
    `Generated by Ardena for Business on ${new Date().toLocaleDateString("en-KE", { day: "numeric", month: "short", year: "numeric" })}`,
    16,
    page - 11
  );
  doc.text("Ardena Platforms Africa Ltd", 194, page - 11, { align: "right" });
}

function sectionTitle(doc, text, y) {
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.setTextColor(MUTE);
  doc.text(text.toUpperCase(), 16, y);
  doc.setDrawColor(LINE);
  doc.line(16, y + 2, 194, y + 2);
  return y + 9;
}

function row(doc, label, value, y, x = 16, w = 178) {
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9.5);
  doc.setTextColor(SOFT);
  doc.text(label, x, y);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(INK);
  doc.text(String(value), x + w, y, { align: "right" });
  return y + 7;
}

/* ---- Rental agreement ---- */

export async function downloadAgreement(b, policy) {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF();
  const days = rentalDays(b.pickup, b.dropoff);
  const total = days * b.rate;

  const biz = getBusiness();
  const bizName = biz.name || "Car Hire";
  const bizLocation = biz.location || "";
  const bizContact = [biz.phone, biz.email].filter(Boolean).join(" · ");

  let y = header(doc, "RENTAL AGREEMENT", `${b.ref} · ${fmtDate(b.created)}`);

  y = sectionTitle(doc, "Parties", y);
  y = row(doc, "Owner / operator", bizLocation ? `${bizName}, ${bizLocation}` : bizName, y);
  if (bizContact) y = row(doc, "Owner contact", bizContact, y);
  y = row(doc, "Renter", b.customer, y);
  if (b.phone) y = row(doc, "Renter phone", b.phone, y);
  y = row(doc, "Identity verification", b.verification, y);
  y += 4;

  y = sectionTitle(doc, "Vehicle & term", y);
  y = row(doc, "Vehicle", `${b.vehicle} (${b.plate})`, y);
  y = row(doc, "Pickup", `${fmtDate(b.pickup)} · ${b.location}`, y);
  y = row(doc, "Return", `${fmtDate(b.dropoff)} by 10:00 AM`, y);
  y = row(doc, "Duration", `${days} day${days > 1 ? "s" : ""}`, y);
  y += 4;

  y = sectionTitle(doc, "Charges", y);
  y = row(doc, "Day rate", kes(b.rate), y);
  y = row(doc, "Rental total", kes(total), y);
  y = row(doc, "Security deposit (refundable)", kes(policy.deposit), y);
  y = row(doc, "Late return penalty", `${kes(policy.lateFeePerHour)} per hour after 10:00 AM`, y);
  y += 4;

  y = sectionTitle(doc, "Terms", y);
  const terms = [
    `1. The renter receives the vehicle in the condition recorded at handover and returns it in the same condition, fuel level included.`,
    `2. The vehicle is due back by 10:00 AM on the return date. Every started hour past that time is charged at ${kes(policy.lateFeePerHour)}.`,
    `3. A refundable security deposit of ${kes(policy.deposit)} is held for the rental and returned after check-in, less any penalties or damage costs.`,
    `4. The renter's identity was verified through the Ardena platform before handover.`,
    `5. The vehicle may only be driven by the named renter within Kenya unless agreed in writing.`,
    `6. Payments are made through the official ${bizName} M-Pesa line. Any other payment request should be treated as fraud.`,
  ];
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.8);
  doc.setTextColor(SOFT);
  terms.forEach((t) => {
    const lines = doc.splitTextToSize(t, 178);
    doc.text(lines, 16, y);
    y += lines.length * 4.4 + 2.2;
  });

  y += 10;
  doc.setDrawColor(INK);
  doc.line(16, y, 86, y);
  doc.line(124, y, 194, y);
  doc.setFontSize(8.5);
  doc.setTextColor(MUTE);
  doc.text(`${bizName} (owner)`, 16, y + 5);
  doc.text(`${b.customer} (renter)`, 124, y + 5);
  doc.text("Date:", 16, y + 12);
  doc.text("Date:", 124, y + 12);

  footer(doc);
  doc.save(`Rental-Agreement-${b.ref}.pdf`);
}

/* ---- Vehicle statement ---- */

export async function downloadVehicleStatement(vehicle, bookings, monthLabel, monthPrefix) {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF();
  const inMonth = bookings.filter(
    (b) => b.plate === vehicle.plate && b.pickup.startsWith(monthPrefix) && b.status !== "Cancelled"
  );

  let y = header(doc, "VEHICLE STATEMENT", `${vehicle.plate} · ${monthLabel}`);

  y = sectionTitle(doc, "Vehicle", y);
  y = row(doc, "Vehicle", `${vehicle.name} (${vehicle.plate})`, y);
  y = row(doc, "Category", vehicle.cat, y);
  y = row(doc, "Day rate", kes(vehicle.rate), y);
  y += 4;

  y = sectionTitle(doc, `Bookings · ${monthLabel}`, y);
  let totalRevenue = 0;
  let totalDays = 0;

  if (inMonth.length === 0) {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9.5);
    doc.setTextColor(SOFT);
    doc.text("No bookings started in this period.", 16, y);
    y += 8;
  } else {
    inMonth.forEach((b) => {
      const days = rentalDays(b.pickup, b.dropoff);
      const amount = days * b.rate;
      totalRevenue += amount;
      totalDays += days;
      doc.setFont("helvetica", "normal");
      doc.setFontSize(9.5);
      doc.setTextColor(SOFT);
      doc.text(`${b.ref} · ${b.customer}`, 16, y);
      doc.setTextColor(MUTE);
      doc.text(`${fmtDate(b.pickup)} – ${fmtDate(b.dropoff)} (${days}d)`, 96, y);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(INK);
      doc.text(kes(amount), 194, y, { align: "right" });
      y += 7;
    });
  }

  y += 2;
  doc.setDrawColor(LINE);
  doc.line(16, y, 194, y);
  y += 8;

  y = row(doc, "Days rented", `${totalDays} day${totalDays === 1 ? "" : "s"}`, y);
  y = row(doc, "Utilisation (30-day month)", `${Math.min(100, Math.round((totalDays / 30) * 100))}%`, y);
  doc.setFontSize(11);
  y = row(doc, "Gross earnings", kes(totalRevenue), y + 2);

  y += 6;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8.5);
  doc.setTextColor(MUTE);
  doc.text(
    doc.splitTextToSize(
      "Share this statement with the vehicle's owner. Amounts are gross rental charges for bookings that started in the period, before any commissions or expenses.",
      178
    ),
    16,
    y
  );

  footer(doc);
  doc.save(`Statement-${vehicle.plate.replace(/\s/g, "")}-${monthLabel.replace(/\s/g, "-")}.pdf`);
}
